"""
Database models and operations for the crypto trading bot.
Handles chat sessions, messages, trading signals, and coin cache with proper indexing.
"""

import sqlite3
import json
import time
import logging
from typing import Optional, List, Dict, Any, Tuple
from datetime import datetime, timezone
from contextlib import contextmanager
from dataclasses import dataclass, asdict
from pathlib import Path

# Configure logging
logger = logging.getLogger(__name__)

# Database configuration
DB_PATH = Path("data/trading_bot.db")
DB_TIMEOUT = 30  # seconds
MAX_RETRIES = 3
RETRY_DELAY = 0.1  # seconds


@dataclass
class ChatSession:
    """Represents a chat session with the AI."""
    id: Optional[int] = None
    session_id: str = ""
    user_id: str = "default"
    title: str = "New Chat"
    created_at: float = 0.0
    updated_at: float = 0.0
    is_active: bool = True
    metadata_json: str = "{}"


@dataclass
class ChatMessage:
    """Represents a single message in a chat session."""
    id: Optional[int] = None
    session_id: str = ""
    role: str = ""  # 'user', 'assistant', 'system'
    content: str = ""
    created_at: float = 0.0
    token_count: int = 0
    metadata_json: str = "{}"


@dataclass
class Signal:
    """Represents a trading signal generated by the AI."""
    id: Optional[int] = None
    symbol: str = ""
    signal_type: str = ""  # 'buy', 'sell', 'neutral'
    confidence: float = 0.0
    price: float = 0.0
    timeframe: str = "1h"
    reason: str = ""
    created_at: float = 0.0
    expires_at: float = 0.0
    is_executed: bool = False
    metadata_json: str = "{}"


@dataclass
class CoinCache:
    """Cached coin data for quick access."""
    id: Optional[int] = None
    symbol: str = ""
    name: str = ""
    price: float = 0.0
    volume_24h: float = 0.0
    market_cap: float = 0.0
    change_24h: float = 0.0
    updated_at: float = 0.0
    metadata_json: str = "{}"


class DatabaseError(Exception):
    """Custom exception for database operations."""
    pass


class DatabaseManager:
    """
    Manages SQLite database operations with connection pooling and retry logic.
    
    Tables:
        - chat_sessions: Store AI chat sessions
        - chat_messages: Store individual messages
        - signals: Store trading signals
        - coin_cache: Cache coin market data
    """
    
    def __init__(self, db_path: Path = DB_PATH):
        """
        Initialize database manager.
        
        Args:
            db_path: Path to SQLite database file
        """
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_database()
        logger.info(f"Database initialized at {self.db_path}")
    
    def _get_connection(self) -> sqlite3.Connection:
        """
        Get a database connection with proper settings.
        
        Returns:
            SQLite connection object
        """
        conn = sqlite3.connect(
            str(self.db_path),
            timeout=DB_TIMEOUT,
            check_same_thread=False
        )
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA foreign_keys=ON")
        conn.execute("PRAGMA busy_timeout=5000")
        return conn
    
    @contextmanager
    def _get_cursor(self):
        """
        Context manager for database cursor with retry logic.
        
        Yields:
            SQLite cursor object
        """
        conn = None
        for attempt in range(MAX_RETRIES):
            try:
                conn = self._get_connection()
                cursor = conn.cursor()
                yield cursor
                conn.commit()
                break
            except sqlite3.Error as e:
                if conn:
                    conn.rollback()
                if attempt < MAX_RETRIES - 1:
                    time.sleep(RETRY_DELAY)
                    continue
                raise DatabaseError(f"Database operation failed after {MAX_RETRIES} attempts: {e}")
            finally:
                if conn:
                    conn.close()
    
    def _init_database(self):
        """Initialize database schema and create tables if they don't exist."""
        try:
            with self._get_cursor() as cursor:
                # Enable WAL mode for better concurrency
                cursor.execute("PRAGMA journal_mode=WAL")
                
                # Create chat_sessions table
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS chat_sessions (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        session_id TEXT UNIQUE NOT NULL,
                        user_id TEXT NOT NULL DEFAULT 'default',
                        title TEXT NOT NULL DEFAULT 'New Chat',
                        created_at REAL NOT NULL,
                        updated_at REAL NOT NULL,
                        is_active INTEGER NOT NULL DEFAULT 1,
                        metadata_json TEXT NOT NULL DEFAULT '{}'
                    )
                """)
                
                # Create chat_messages table
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS chat_messages (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        session_id TEXT NOT NULL,
                        role TEXT NOT NULL CHECK(role IN ('user', 'assistant', 'system')),
                        content TEXT NOT NULL,
                        created_at REAL NOT NULL,
                        token_count INTEGER NOT NULL DEFAULT 0,
                        metadata_json TEXT NOT NULL DEFAULT '{}',
                        FOREIGN KEY (session_id) REFERENCES chat_sessions(session_id)
                    )
                """)
                
                # Create signals table
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS signals (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        symbol TEXT NOT NULL,
                        signal_type TEXT NOT NULL CHECK(signal_type IN ('buy', 'sell', 'neutral')),
                        confidence REAL NOT NULL CHECK(confidence >= 0 AND confidence <= 1),
                        price REAL NOT NULL,
                        timeframe TEXT NOT NULL DEFAULT '1h',
                        reason TEXT NOT NULL DEFAULT '',
                        created_at REAL NOT NULL,
                        expires_at REAL NOT NULL,
                        is_executed INTEGER NOT NULL DEFAULT 0,
                        metadata_json TEXT NOT NULL DEFAULT '{}'
                    )
                """)
                
                # Create coin_cache table
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS coin_cache (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        symbol TEXT UNIQUE NOT NULL,
                        name TEXT NOT NULL DEFAULT '',
                        price REAL NOT NULL DEFAULT 0,
                        volume_24h REAL NOT NULL DEFAULT 0,
                        market_cap REAL NOT NULL DEFAULT 0,
                        change_24h REAL NOT NULL DEFAULT 0,
                        updated_at REAL NOT NULL,
                        metadata_json TEXT NOT NULL DEFAULT '{}'
                    )
                """)
                
                # Create indexes for better query performance
                self._create_indexes(cursor)
                
                logger.info("Database schema initialized successfully")
                
        except sqlite3.Error as e:
            raise DatabaseError(f"Failed to initialize database: {e}")
    
    def _create_indexes(self, cursor: sqlite3.Cursor):
        """
        Create indexes for optimized queries.
        
        Args:
            cursor: SQLite cursor object
        """
        indexes = [
            # Chat sessions indexes
            "CREATE INDEX IF NOT EXISTS idx_chat_sessions_user_id ON chat_sessions(user_id)",
            "CREATE INDEX IF NOT EXISTS idx_chat_sessions_updated ON chat_sessions(updated_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_chat_sessions_active ON chat_sessions(is_active)",
            
            # Chat messages indexes
            "CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages(session_id)",
            "CREATE INDEX IF NOT EXISTS idx_chat_messages_created ON chat_messages(created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_chat_messages_role ON chat_messages(role)",
            
            # Signals indexes
            "CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol)",
            "CREATE INDEX IF NOT EXISTS idx_signals_type ON signals(signal_type)",
            "CREATE INDEX IF NOT EXISTS idx_signals_created ON signals(created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_signals_expires ON signals(expires_at)",
            "CREATE INDEX IF NOT EXISTS idx_signals_executed ON signals(is_executed)",
            "CREATE INDEX IF NOT EXISTS idx_signals_symbol_timeframe ON signals(symbol, timeframe)",
            
            # Coin cache indexes
            "CREATE INDEX IF NOT EXISTS idx_coin_cache_symbol ON coin_cache(symbol)",
            "CREATE INDEX IF NOT EXISTS idx_coin_cache_updated ON coin_cache(updated_at DESC)",
        ]
        
        for index_sql in indexes:
            try:
                cursor.execute(index_sql)
            except sqlite3.Error as e:
                logger.warning(f"Failed to create index: {e}")
    
    # ==================== Chat Session Operations ====================
    
    def create_chat_session(self, session: ChatSession) -> int:
        """
        Create a new chat session.
        
        Args:
            session: ChatSession object
            
        Returns:
            Session ID
        """
        now = time.time()
        session.created_at = now
        session.updated_at = now
        
        with self._get_cursor() as cursor:
            cursor.execute("""
                INSERT INTO chat_sessions (session_id, user_id, title, created_at, updated_at, is_active, metadata_json)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (
                session.session_id,
                session.user_id,
                session.title,
                session.created_at,
                session.updated_at,
                int(session.is_active),
                session.metadata_json
            ))
            return cursor.lastrowid
    
    def get_chat_session(self, session_id: str) -> Optional[Dict[str, Any]]:
        """
        Get a chat session by ID.
        
        Args:
            session_id: Session identifier
            
        Returns:
            Session dict or None
        """
        with self._get_cursor() as cursor:
            cursor.execute(
                "SELECT * FROM chat_sessions WHERE session_id = ?",
                (session_id,)
            )
            row = cursor.fetchone()
            return dict(row) if row else None
    
    def get_user_sessions(self, user_id: str = "default", limit: int = 50) -> List[Dict[str, Any]]:
        """
        Get all sessions for a user.
        
        Args:
            user_id: User identifier
            limit: Maximum number of sessions to return
            
        Returns:
            List of session dicts
        """
        with self._get_cursor() as cursor:
            cursor.execute("""
                SELECT * FROM chat_sessions 
                WHERE user_id = ? AND is_active = 1
                ORDER BY updated_at DESC
                LIMIT ?
            """, (user_id, limit))
            return [dict(row) for row in cursor.fetchall()]
    
    def update_chat_session(self, session_id: str, **kwargs) -> bool:
        """
        Update a chat session.
        
        Args:
            session_id: Session identifier
            **kwargs: Fields to update
            
        Returns:
            True if successful
        """
        allowed_fields = {'title', 'is_active', 'metadata_json'}
        updates = {k: v for k, v in kwargs.items() if k in allowed_fields}
        
        if not updates:
            return False
        
        updates['updated_at'] = time.time()
        set_clause = ", ".join(f"{k} = ?" for k in updates.keys())
        values = list(updates.values()) + [session_id]
        
        with self._get_cursor() as cursor:
            cursor.execute(
                f"UPDATE chat_sessions SET {set_clause} WHERE session_id = ?",
                values
            )
            return cursor.rowcount > 0
    
    def delete_chat_session(self, session_id: str) -> bool:
        """
        Soft delete a chat session.
        
        Args:
            session_id: Session identifier
            
        Returns:
            True if successful
        """
        return self.update_chat_session(session_id, is_active=False)
    
    # ==================== Chat Message Operations ====================
    
    def add_message(self, message: ChatMessage) -> int:
        """
        Add a message to a chat session.
        
        Args:
            message: ChatMessage object
            
        Returns:
            Message ID
        """
        if not message.created_at:
            message.created_at = time.time()
        
        with self._get_cursor() as cursor:
            cursor.execute("""
                INSERT INTO chat_messages (session_id, role, content, created_at, token_count, metadata_json)
                VALUES (?, ?, ?, ?, ?, ?)
            """, (
                message.session_id,
                message.role,
                message.content,
                message.created_at,
                message.token_count,
                message.metadata_json
            ))
            
            # Update session's updated_at timestamp
            cursor.execute(
                "UPDATE chat_sessions SET updated_at = ? WHERE session_id = ?",
                (time.time(), message.session_id)
            )
            
            return cursor.lastrowid
    
    def get_session_messages(self, session_id: str, limit: int = 100) -> List[Dict[str, Any]]:
        """
        Get messages for a session.
        
        Args:
            session_id: Session identifier
            limit: Maximum number of messages to return
            
        Returns:
            List of message dicts
        """
        with self._get_cursor() as cursor:
            cursor.execute("""
                SELECT * FROM chat_messages 
                WHERE session_id = ?
                ORDER BY created_at ASC
                LIMIT ?
            """, (session_id, limit))
            return [dict(row) for row in cursor.fetchall()]
    
    def get_recent_messages(self, session_id: str, count: int = 10) -> List[Dict[str, Any]]:
        """
        Get most recent messages from a session.
        
        Args:
            session_id: Session identifier
            count: Number of messages to return
            
        Returns:
            List of message dicts
        """
        with self._get_cursor() as cursor:
            cursor.execute("""
                SELECT * FROM chat_messages 
                WHERE session_id = ?
                ORDER BY created_at DESC
                LIMIT ?
            """, (session_id, count))
            return [dict(row) for row in reversed(cursor.fetchall())]
    
    def delete_session_messages(self, session_id: str) -> bool:
        """
        Delete all messages for a session.
        
        Args:
            session_id: Session identifier
            
        Returns:
            True if successful
        """
        with self._get_cursor() as cursor:
            cursor.execute(
                "DELETE FROM chat_messages WHERE session_id = ?",
                (session_id,)
            )
            return True
    
    # ==================== Signal Operations ====================
    
    def add_signal(self, signal: Signal) -> int:
        """
        Add a trading signal.
        
        Args:
            signal: Signal object
            
        Returns:
            Signal ID
        """
        if not signal.created_at:
            signal.created_at = time.time()
        if not signal.expires_at:
            signal.expires_at = signal.created_at + 86400  # Default 24h expiry
        
        with self._get_cursor() as cursor:
            cursor.execute("""
                INSERT INTO signals (symbol, signal_type, confidence, price, timeframe, reason, created_at, expires_at, is_executed, metadata_json)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                signal.symbol.upper(),
                signal.signal_type,
                max(0.0, min(1.0, signal.confidence)),
                signal.price,
                signal.timeframe,
                signal.reason,
                signal.created_at,
                signal.expires_at,
                int(signal.is_executed),
                signal.metadata_json
            ))
            return cursor.lastrowid
    
    def get_active_signals(self, symbol: Optional[str] = None) -> List[Dict[str, Any]]:
        """
        Get active (non-expired, non-executed) signals.
        
        Args:
            symbol: Optional symbol filter
            
        Returns:
            List of signal dicts
        """
        now = time.time()
        
        with self._get_cursor() as cursor:
            if symbol:
                cursor.execute("""
                    SELECT * FROM signals 
                    WHERE symbol = ? AND expires_at > ? AND is_executed = 0
                    ORDER BY created_at DESC
                """, (symbol.upper(), now))
            else:
                cursor.execute("""
                    SELECT * FROM signals 
                    WHERE expires_at > ? AND is_executed = 0
                    ORDER BY created_at DESC
                """, (now,))
            
            return [dict(row) for row in cursor.fetchall()]
    
    def get_signals_by_symbol(self, symbol: str, limit: int = 50) -> List[Dict[str, Any]]:
        """
        Get signals for a specific symbol.
        
        Args:
            symbol: Trading symbol
            limit: Maximum number of signals to return
            
        Returns:
            List of signal dicts
        """
        with self._get_cursor() as cursor:
            cursor.execute("""
                SELECT * FROM signals 
                WHERE symbol = ?
                ORDER BY created_at DESC
                LIMIT ?
            """, (symbol.upper(), limit))
            return [dict(row) for row in cursor.fetchall()]
    
    def mark_signal_executed(self, signal_id: int) -> bool:
        """
        Mark a signal as executed.
        
        Args:
            signal_id: Signal identifier
            
        Returns:
            True if successful
        """
        with self._get_cursor() as cursor:
            cursor.execute(
                "UPDATE signals SET is_executed = 1 WHERE id = ?",
                (signal_id,)
            )
            return cursor.rowcount > 0
    
    def cleanup_expired_signals(self) -> int:
        """
        Remove expired signals from database.
        
        Returns:
            Number of deleted signals
        """
        now = time.time()
        with self._get_cursor() as cursor:
            cursor.execute(
                "DELETE FROM signals WHERE expires_at < ?",
                (now,)
            )
            deleted_count = cursor.rowcount
            if deleted_count > 0:
                logger.info(f"Cleaned up {deleted_count} expired signals")
            return deleted_count
    
    # ==================== Coin Cache Operations ====================
    
    def update_coin_cache(self, coin: CoinCache) -> bool:
        """
        Update or insert coin cache data.
        
        Args:
            coin: CoinCache object
            
        Returns:
            True if successful
        """
        coin.updated_at = time.time()
        
        with self._get_cursor() as cursor:
            cursor.execute("""
                INSERT INTO coin_cache (symbol, name, price, volume_24h, market_cap, change_24h, updated_at, metadata_json)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(symbol) DO UPDATE SET
                    name = excluded.name,
                    price = excluded.price,
                    volume_24h = excluded.volume_24h,
                    market_cap = excluded.market_cap,
                    change_24h = excluded.change_24h,
                    updated_at = excluded.updated_at,
                    metadata_json = excluded.metadata_json
            """, (
                coin.symbol.upper(),
                coin.name,
                coin.price,
                coin.volume_24h,
                coin.market_cap,
                coin.change_24h,
                coin.updated_at,
                coin.metadata_json
            ))
            return True
    
    def bulk_update_coin_cache(self, coins: List[CoinCache]) -> int:
        """
        Bulk update coin cache data.
        
        Args:
            coins: List of CoinCache objects
            
        Returns:
            Number of updated coins
        """
        updated_count = 0
        for coin in coins:
            try:
                if self.update_coin_cache(coin):
                    updated_count += 1
            except Exception as e:
                logger.error(f"Failed to update cache for {coin.symbol}: {e}")
        
        return updated_count
    
    def get_coin_cache(self, symbol: str) -> Optional[Dict[str, Any]]:
        """
        Get cached coin data.
        
        Args:
            symbol: Coin symbol
            
        Returns:
            Coin cache dict or None
        """
        with self._get_cursor() as cursor:
            cursor.execute(
                "SELECT * FROM coin_cache WHERE symbol = ?",
                (symbol.upper(),)
            )
            row = cursor.fetchone()
            return dict(row) if row else None
    
    def get_all_cached_coins(self) -> List[Dict[str, Any]]:
        """
        Get all cached coins.
        
        Returns:
            List of coin cache dicts
        """
        with self._get_cursor() as cursor:
            cursor.execute("""
                SELECT * FROM coin_cache 
                ORDER BY market_cap DESC
            """)
            return [dict(row) for row in cursor.fetchall()]
    
    def get_stale_coins(self, max_age: float = 300.0) -> List[Dict[str, Any]]:
        """
        Get coins that haven't been updated recently.
        
        Args:
            max_age: Maximum age in seconds before considered stale
            
        Returns:
            List of stale coin cache dicts
        """
        cutoff_time = time.time() - max_age
        with self._get_cursor() as cursor:
            cursor.execute("""
                SELECT * FROM coin_cache 
                WHERE updated_at < ?
                ORDER BY updated_at ASC
            """, (cutoff_time,))
            return [dict(row) for row in cursor.fetchall()]
    
    def cleanup_stale_coins(self, max_age: float = 86400.0) -> int:
        """
        Remove stale coin cache entries.
        
        Args:
            max_age: Maximum age in seconds before removal
            
        Returns:
            Number of deleted entries
        """
        cutoff_time = time.time() - max_age
        with self._get_cursor() as cursor:
            cursor.execute(
                "DELETE FROM coin_cache WHERE updated_at < ?",
                (cutoff_time,)
            )
            deleted_count = cursor.rowcount
            if deleted_count > 0:
                logger.info(f"Cleaned up {deleted_count} stale coin cache entries")
            return deleted_count
    
    # ==================== Utility Operations ====================
    
    def get_database_stats(self) -> Dict[str, Any]:
        """
        Get database statistics.
        
        Returns:
            Dictionary with table statistics
        """
        stats = {}
        tables = ['chat_sessions', 'chat_messages', 'signals', 'coin_cache']
        
        with self._get_cursor() as cursor:
            for table in tables:
                cursor.execute(f"SELECT COUNT(*) as count FROM {table}")
                row = cursor.fetchone()
                stats[table] = row['count'] if row else 0
        
        # Get database file size
        try:
            stats['db_size_mb'] = round(self.db_path.stat().st_size / (1024 * 1024), 2)
        except OSError:
            stats['db_size_mb'] = 0.0
        
        return stats
    
    def vacuum_database(self) -> bool:
        """
        Vacuum the database to reclaim space.
        
        Returns:
            True if successful
        """
        try:
            with self._get_cursor() as cursor:
                cursor.execute("VACUUM")
                logger.info("Database vacuum completed")
                return True
        except sqlite3.Error as e:
            logger.error(f"Database vacuum failed: {e}")
            return False
    
    def backup_database(self, backup_path: Path) -> bool:
        """
        Create a backup of the database.
        
        Args:
            backup_path: Path for backup file
            
        Returns:
            True if successful
        """
        try:
            backup_path = Path(backup_path)
            backup_path.parent.mkdir(parents=True, exist_ok=True)
            
            with self._get_connection() as conn:
                backup_conn = sqlite3.connect(str(backup_path))
                conn.backup(backup_conn)
                backup_conn.close()
            
            logger.info(f"Database backed up to {backup_path}")
            return True
        except (sqlite3.Error, OSError) as e:
            logger.error(f"Database backup failed: {e}")
            return False


# Singleton instance for global use
db = DatabaseManager()


def get_database() -> DatabaseManager:
    """
    Get the global database instance.
    
    Returns:
        DatabaseManager instance
    """
    return db